<!-- JS here -->
    <script src="<?= base_url(); ?>assets/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="<?= base_url(); ?>assets/js/bootstrap.bundle.min.js"></script>
    <script src="<?= base_url(); ?>assets/js/jquery.magnific-popup.min.js"></script>
    <script src="<?= base_url(); ?>assets/js/jquery.odometer.min.js"></script>
    <script src="<?= base_url(); ?>assets/js/jquery.appear.js"></script>
    <script src="<?= base_url(); ?>assets/js/gsap.js"></script>
    <script src="<?= base_url(); ?>assets/js/ScrollTrigger.js"></script>
    <script src="<?= base_url(); ?>assets/js/SplitText.js"></script>
    <script src="<?= base_url(); ?>assets/js/gsap-animation.js"></script>
    <script src="<?= base_url(); ?>assets/js/jquery.parallaxScroll.min.js"></script>
    <script src="<?= base_url(); ?>assets/js/swiper-bundle.js"></script>
    <script src="<?= base_url(); ?>assets/js/ajax-form.js"></script>
    <script src="<?= base_url(); ?>assets/js/wow.min.js"></script>
    <script src="<?= base_url(); ?>assets/js/aos.js"></script>
    <script src="<?= base_url(); ?>assets/js/main.js"></script>